# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Java CI with Gradle and unittest

on:
  push:
    branches: [develop]
  pull_request:
    branches: [develop]

  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Instalacion JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Compilación y ejecución de permisos para gradlew
        run: chmod +x gradlew
      - name: Build with Gradle
        run: ./gradlew build
